version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=travelDB
